## Data Loading

In [5]:
import pandas as pd
df = pd.read_csv("../data/raw/styles.csv")

In [3]:
df.head()

,id,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName,Unnamed: 10,Unnamed: 11
0,15970,Men,Apparel,Topwear,Shirts,Navy Blue,Fall,2011.0,Casual,Turtle Check Men Navy Blue Shirt,NaN,NaN
1,39386,Men,Apparel,Bottomwear,Jeans,Blue,Summer,2012.0,Casual,Peter England Men Party Blue Jeans,NaN,NaN
2,59263,Women,Accessories,Watches,Watches,Silver,Winter,2016.0,Casual,Titan Women Silver Watch,NaN,NaN
3,21379,Men,Apparel,Bottomwear,Track Pants,Black,Fall,2011.0,Casual,Manchester United Men Solid Black Track Pants,NaN,NaN
4,53759,Men,Apparel,Topwear,Tshirts,Grey,Summer,2012.0,Casual,Puma Men Grey T-shirt,NaN,NaN

## Value Exploration

In [4]:
df['articleType'].value_counts()

articleType
Tshirts                7070
Shirts                 3217
Casual Shoes           2846
Watches                2542
Sports Shoes           2036
                       ...
Cushion Covers            1
Mens Grooming Kit         1
Body Wash and Scrub       1
Suits                     1
Ipad                      1
Name: count, Length: 143, dtype: int64

In [5]:
df['baseColour'].value_counts()

baseColour
Black                9732
White                5540
Blue                 4922
Brown                3494
Grey                 2741
Red                  2458
Green                2116
Pink                 1861
Navy Blue            1791
Purple               1643
Silver               1090
Yellow                779
Beige                 749
Gold                  629
Maroon                581
Orange                530
Olive                 410
Multi                 394
Cream                 390
Steel                 315
Charcoal              228
Peach                 195
Off White             182
Skin                  179
Lavender              162
Grey Melange          146
Khaki                 139
Magenta               129
Teal                  120
Tan                   114
Mustard                97
Bronze                 95
Copper                 86
Turquoise Blue         69
Rust                   66
Burgundy               45
Metallic               43
Coffee Brown           31
Mauve                  29
Rose                   28
Nude                   23
Sea Green              22
Mushroom Brown         16
Taupe                  11
Lime Green              6
Fluorescent Green       5
Name: count, dtype: int64

In [6]:
df['usage'].value_counts()

usage
Casual          34414
Sports           4025
Ethnic           3208
Formal           2359
Smart Casual       67
Party              29
Travel             26
Home                1
Name: count, dtype: int64

In [7]:
df['gender'].value_counts()

gender
Men       22165
Women     18632
Unisex     2164
Boys        830
Girls       655
Name: count, dtype: int64

In [8]:
df.shape

(44446, 12)

In [9]:
df.columns

Index(['id', 'gender', 'masterCategory', 'subCategory', 'articleType',
       'baseColour', 'season', 'year', 'usage', 'productDisplayName',
       'Unnamed: 10', 'Unnamed: 11'],
      dtype='object')

In [10]:
df['articleType'].value_counts().head(30)

articleType
Tshirts                  7070
Shirts                   3217
Casual Shoes             2846
Watches                  2542
Sports Shoes             2036
Kurtas                   1844
Tops                     1762
Handbags                 1759
Heels                    1323
Sunglasses               1073
Wallets                   936
Flip Flops                916
Sandals                   897
Briefs                    849
Belts                     813
Backpacks                 724
Socks                     686
Formal Shoes              637
Perfume and Body Mist     614
Jeans                     609
Shorts                    547
Trousers                  530
Flats                     500
Bra                       477
Dresses                   464
Sarees                    427
Earrings                  417
Deodorant                 347
Nail Polish               329
Lipstick                  315
Name: count, dtype: int64

In [11]:
df['baseColour'].value_counts().head(20)

baseColour
Black        9732
White        5540
Blue         4922
Brown        3494
Grey         2741
Red          2458
Green        2116
Pink         1861
Navy Blue    1791
Purple       1643
Silver       1090
Yellow        779
Beige         749
Gold          629
Maroon        581
Orange        530
Olive         410
Multi         394
Cream         390
Steel         315
Name: count, dtype: int64

In [12]:
df['usage'].value_counts()

usage
Casual          34414
Sports           4025
Ethnic           3208
Formal           2359
Smart Casual       67
Party              29
Travel             26
Home                1
Name: count, dtype: int64

In [6]:
## Remove unwanted columns
df = df.drop(columns=['Unnamed: 10','Unnamed: 11'])

In [15]:
df['articleType'].unique()

array(['Shirts', 'Jeans', 'Watches', 'Track Pants', 'Tshirts', 'Socks',
       'Casual Shoes', 'Belts', 'Flip Flops', 'Handbags', 'Tops', 'Bra',
       'Sandals', 'Shoe Accessories', 'Sweatshirts', 'Deodorant',
       'Formal Shoes', 'Bracelet', 'Lipstick', 'Flats', 'Kurtas',
       'Waistcoat', 'Sports Shoes', 'Shorts', 'Briefs', 'Sarees',
       'Perfume and Body Mist', 'Heels', 'Sunglasses', 'Innerwear Vests',
       'Pendant', 'Nail Polish', 'Laptop Bag', 'Scarves', 'Rain Jacket',
       'Dresses', 'Night suits', 'Skirts', 'Wallets', 'Blazers', 'Ring',
       'Kurta Sets', 'Clutches', 'Shrug', 'Backpacks', 'Caps', 'Trousers',
       'Earrings', 'Camisoles', 'Boxers', 'Jewellery Set', 'Dupatta',
       'Capris', 'Lip Gloss', 'Bath Robe', 'Mufflers', 'Tunics',
       'Jackets', 'Trunk', 'Lounge Pants', 'Face Wash and Cleanser',
       'Necklace and Chains', 'Duffel Bag', 'Sports Sandals',
       'Foundation and Primer', 'Sweaters', 'Free Gifts', 'Trolley Bag',
       'Tracksuits', 'Swimwear', 'Shoe Laces', 'Fragrance Gift Set',
       'Bangle', 'Nightdress', 'Ties', 'Baby Dolls', 'Leggings',
       'Highlighter and Blush', 'Travel Accessory', 'Kurtis',
       'Mobile Pouch', 'Messenger Bag', 'Lip Care', 'Face Moisturisers',
       'Compact', 'Eye Cream', 'Accessory Gift Set', 'Beauty Accessory',
       'Jumpsuit', 'Kajal and Eyeliner', 'Water Bottle', 'Suspenders',
       'Lip Liner', 'Robe', 'Salwar and Dupatta', 'Patiala', 'Stockings',
       'Eyeshadow', 'Headband', 'Tights', 'Nail Essentials', 'Churidar',
       'Lounge Tshirts', 'Face Scrub and Exfoliator', 'Lounge Shorts',
       'Gloves', 'Mask and Peel', 'Wristbands', 'Tablet Sleeve',
       'Ties and Cufflinks', 'Footballs', 'Stoles', 'Shapewear',
       'Nehru Jackets', 'Salwar', 'Cufflinks', 'Jeggings', 'Hair Colour',
       'Concealer', 'Rompers', 'Body Lotion', 'Sunscreen', 'Booties',
       'Waist Pouch', 'Hair Accessory', 'Rucksacks', 'Basketballs',
       'Lehenga Choli', 'Clothing Set', 'Mascara', 'Toner',
       'Cushion Covers', 'Key chain', 'Makeup Remover', 'Lip Plumper',
       'Umbrellas', 'Face Serum and Gel', 'Hat', 'Mens Grooming Kit',
       'Rain Trousers', 'Body Wash and Scrub', 'Suits', 'Ipad'],
      dtype=object)

In [16]:
df['masterCategory'].value_counts()

masterCategory
Apparel           21400
Accessories       11289
Footwear           9222
Personal Care      2404
Free Items          105
Sporting Goods       25
Home                  1
Name: count, dtype: int64

In [17]:
df['subCategory'].value_counts()

subCategory
Topwear                     15405
Shoes                        7344
Bags                         3055
Bottomwear                   2694
Watches                      2542
Innerwear                    1808
Jewellery                    1080
Eyewear                      1073
Fragrance                    1012
Sandal                        963
Wallets                       933
Flip Flops                    915
Belts                         811
Socks                         698
Lips                          527
Dress                         478
Loungewear and Nightwear      470
Saree                         427
Nails                         329
Makeup                        307
Headwear                      293
Ties                          258
Accessories                   143
Scarves                       118
Cufflinks                     108
Apparel Set                   106
Free Gifts                    104
Stoles                         90
Skin Care                      77
Skin                           69
Eyes                           43
Mufflers                       38
Shoe Accessories               24
Sports Equipment               21
Gloves                         20
Hair                           19
Bath and Body                  12
Water Bottle                    7
Perfumes                        6
Umbrellas                       6
Beauty Accessories              4
Wristbands                      4
Sports Accessories              3
Home Furnishing                 1
Vouchers                        1
Name: count, dtype: int64

In [18]:
df['gender'].value_counts()

gender
Men       22165
Women     18632
Unisex     2164
Boys        830
Girls       655
Name: count, dtype: int64

In [19]:
df['season'].value_counts()

season
Summer    21476
Fall      11445
Winter     8519
Spring     2985
Name: count, dtype: int64

In [20]:
df[['articleType','subCategory']].drop_duplicates().head(50)

               articleType               subCategory
0                   Shirts                   Topwear
1                    Jeans                Bottomwear
2                  Watches                   Watches
3              Track Pants                Bottomwear
4                  Tshirts                   Topwear
8                    Socks                     Socks
10            Casual Shoes                     Shoes
11                   Belts                     Belts
12              Flip Flops                Flip Flops
13                Handbags                      Bags
17                    Tops                   Topwear
18                     Bra                 Innerwear
21                 Sandals                    Sandal
22        Shoe Accessories          Shoe Accessories
23             Sweatshirts                   Topwear
24               Deodorant                 Fragrance
25            Formal Shoes                     Shoes
26                Bracelet                 Jewellery
28                Lipstick                      Lips
34                   Flats                     Shoes
35                  Kurtas                   Topwear
44               Waistcoat                   Topwear
45            Sports Shoes                     Shoes
46                  Shorts                Bottomwear
47                  Briefs                 Innerwear
60                  Sarees                     Saree
66   Perfume and Body Mist                 Fragrance
76                   Heels                     Shoes
80              Sunglasses                   Eyewear
83         Innerwear Vests                 Innerwear
85                 Pendant                 Jewellery
87             Nail Polish                     Nails
88              Laptop Bag                      Bags
91                 Scarves                   Scarves
92             Rain Jacket                   Topwear
94                 Dresses                     Dress
97             Night suits  Loungewear and Nightwear
100                 Skirts                Bottomwear
111                Wallets                   Wallets
117                Blazers                   Topwear
123                   Ring                 Jewellery
134             Kurta Sets               Apparel Set
135               Clutches                      Bags
140                  Shrug                   Topwear
145              Backpacks                      Bags
152                   Caps                  Headwear
166               Trousers                Bottomwear
175               Earrings                 Jewellery
195              Camisoles                 Innerwear
196                 Boxers                 Innerwear

## Tops, Bottoms and Footwears

In [13]:
tops = [
    'Tshirts',
    'Shirts',
    'Kurtas',
    'Tops',
    'Sweatshirts',
    'Sweaters',
    'Jackets'
]

bottoms = [
    'Jeans',
    'Trousers',
    'Shorts',
    'Track Pants'
]

footwear = [
    'Casual Shoes',
    'Sports Shoes',
    'Formal Shoes'
]

In [7]:
# Keep only outfit-related items
relevant_items = tops + bottoms + footwear

fashion_df = df[df['articleType'].isin(relevant_items)].copy()

In [8]:
fashion_df.shape

fashion_df['articleType'].value_counts()

fashion_df['gender'].value_counts()

fashion_df['usage'].value_counts()

usage
Casual          19062
Sports           3547
Ethnic           2031
Formal           1781
Smart Casual       38
Party               5
Travel              1
Name: count, dtype: int64

In [9]:
fashion_df.to_csv(
    '../data/processed/fashion_products.csv',
    index=False
)

In [10]:
fashion_df = df[df['articleType'].isin(relevant_items)]

fashion_df['articleType'].value_counts()

articleType
Tshirts         7070
Shirts          3217
Casual Shoes    2846
Sports Shoes    2036
Kurtas          1844
Tops            1762
Heels           1323
Flip Flops       916
Sandals          897
Formal Shoes     637
Jeans            609
Shorts           547
Trousers         530
Flats            500
Track Pants      304
Sweatshirts      285
Sweaters         277
Jackets          258
Leggings         177
Capris           175
Skirts           128
Jeggings          34
Salwar            32
Churidar          30
Rain Jacket       18
Waistcoat         15
Blazers            8
Shrug              6
Name: count, dtype: int64

In [12]:
fashion_df['gender'].value_counts()

gender
Men       15882
Women      8674
Boys        788
Unisex      606
Girls       531
Name: count, dtype: int64

In [14]:
mens_df = fashion_df[
    (fashion_df['gender'] == 'Men') &
    (fashion_df['articleType'].isin(
        tops + bottoms + footwear
    ))
].copy()

In [15]:
mens_df.shape

(14612, 10)

In [16]:
mens_df['articleType'].value_counts()

articleType
Tshirts         5246
Shirts          2844
Casual Shoes    2247
Sports Shoes    1590
Formal Shoes     637
Trousers         428
Shorts           386
Jeans            332
Sweatshirts      222
Track Pants      217
Jackets          195
Sweaters         189
Kurtas            78
Tops               1
Name: count, dtype: int64

In [17]:
mens_df.to_csv(
    '../data/processed/mens_fashion.csv',
    index=False
)